{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper.fullname" . }}-db
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ required "database.password is required when not using existingSecret" .Values.database.password | b64enc }}
{{- end }}
