services:
  # codeforge_core:
  #   image: codeforge_gatekeeper:0.0.2
  #   environment:
  #     DATABASE_URL: postgresql://postgres:test@database:5432
  #   ports:
  #     - "8081:8081"
  database:
    image: public.ecr.aws/docker/library/postgres:14.21-alpine3.23
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ../../sql/auth:/docker-entrypoint-initdb.d
